name: Prune Issues
on:
  workflow_dispatch: # Allow manual triggering
jobs:
  prune-issues:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install PyGithub
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Prune Issues
        run: |
          python prune_issues.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
