name: Folder Commit Checker
on:
  schedule:
    - cron: '0 0 * * 0' # Run weekly on Sundays
jobs:
  check-folders:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install PyGithub
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run Folder Commit Checker
        run: |
          python folder_commit_checker.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
